name: fhir-emr-tests
services:
    sdc:
        image: bedasoftware/fhir-sdc:develop
        depends_on:
            devbox-healthcheck:
                condition: service_healthy
        links:
            - devbox
        env_file:
            - .env.sdc
        # Colored logs
        tty: true
    devbox:
        image: healthsamurai/aidboxone:edge
        depends_on:
            - devbox-db_test
            - build-seeds
        links:
            - 'devbox-db_test:database'
        ports:
            - '8081:8080'
        env_file:
            - .env.aidbox
            - .env
        volumes:
            - ./config:/var/config:cached
            - ./zenproject:/zenproject
    devbox-db_test:
        image: 'healthsamurai/aidboxdb:13.2'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: devbox
    devbox-healthcheck:
        image: curlimages/curl
        entrypoint: /bin/sleep 10000
        links:
            - devbox
        depends_on:
            - devbox
        healthcheck:
            test: curl --fail http://devbox:8080/__healthcheck || exit 1
            interval: 1s
            timeout: 20s
            retries: 100
    build-seeds:
        build:
            context: .
            dockerfile: Dockerfile.seeds
        volumes:
            - ./zenproject:/app/zenproject
            - ./resources/seeds:/app/resources/seeds
