name: main
on:
    push:
        branches:
            - master
jobs:
    Test:
        runs-on: ubuntu-latest
        env:
            AIDBOX_LICENSE: ${{ secrets.AIDBOX_LICENSE }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install deps
              run: yarn
            - name: Check types
              run: yarn typecheck
            - name: Prepare secrets
              run: echo AIDBOX_LICENSE=${AIDBOX_LICENSE} > .env
            - name: Run aidbox
              run: make up
            - name: Show logs
              if: ${{ failure() }}
              run: docker-compose logs
            - name: Run tests
              run: yarn test
            - run: yarn build:web
    Release:
        # needs: Test
        runs-on: ubuntu-latest
        env:
            BUILD_IMAGE: bedasoftware/fhir-emr:master
            DISABLE_ESLINT_PLUGIN: true
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Prepare config
              run: cp shared/src/config.production.ts shared/src/config.ts
            - name: Install deps
              run: yarn
            - run: yarn compile
            - run: cd web && yarn build
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1
            - run: docker run --rm --privileged tonistiigi/binfmt --install all
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}
            - run: >-
                  docker buildx build --platform linux/arm64,linux/amd64
                  -f Dockerfile.web.release
                  --push -t ${{ env.BUILD_IMAGE }} .
    Deploy:
        needs: Release
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        steps:
            - uses: actions/checkout@v2
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@v2.1.1
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  ARGS: '-rltgoDzvO'
                  SOURCE: './zrc/'
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: '~/fhir-emr-zrc'
            - name: Restart
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: 22
                  script_stop: true
                  script: |
                      cd ~/web
                      make restart
                      echo Current branch is ${{ github.ref }}
